apiVersion: v1
kind: Service
metadata:
  name: ${{ values.frontendName }}-service
spec:
  selector:
    app: ${{ values.frontendName }}-deployment
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  type: ClusterIP